USE brynikglqwpbdrnw1eak;
CREATE TABLE Shipments (
	SHIPMENT_ID DECIMAL NOT NULL,
    TRANSACTION_TOTAL_COST FLOAT ,
    SHIPMENT_PRICE FLOAT ,
    SHIPMENT_ADDRESS VARCHAR(255),
    
    PRIMARY KEY (SHIPMENT_ID)
);

CREATE TABLE Users (
	USER_ID DECIMAL, # Foreign key relative to BUYER_ID in Transaction
    USER_LNAME VARCHAR(255),
    USER_FNAME VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    USER_DOB DATE,
    USER_ADDRESS VARCHAR(255),
    USER_ZIPCODE VARCHAR(255),
    
    PRIMARY KEY (USER_ID)
    #FOREIGN KEY (USER_ID) REFERENCES Transaction(BUYER_ID)
    
);

CREATE TABLE Inventory (
	ITEM_ID DECIMAL NOT NULL,
    ITEM_NAME VARCHAR(255),
    ITEM_CATEGORY VARCHAR(255),
    ITEM_STOCK INT,
    
    PRIMARY KEY(ITEM_ID)
);

CREATE TABLE Listing ( 
	LISTING_ID DECIMAL NOT NULL,
    USER_ID DECIMAL ,
    ITEM_ID DECIMAL,
    ITEM_COST FLOAT,
	
    PRIMARY KEY (LISTING_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES Inventory(ITEM_ID)
);

CREATE TABLE Transaction (
	TRANSACTION_ID DECIMAL NOT NULL,
    BUYER_ID DECIMAL, # Foreign key relative to USER_ID in USER TABLE
    TRANS_COST FLOAT,
    LISTING_ID DECIMAL,
    ITEM_QUANTITY INT,
    
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (BUYER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (LISTING_ID) REFERENCES Listing(LISTING_ID)
);